import { createSlice } from "@reduxjs/toolkit";

const createNewPostSlice = createSlice({
    name: 'overlay',
    initialState: {
        isShowCreateNewPost: false,
        step: 'first',
        isOpenModal: false,
        filters: [
            { id: 1, name: 'Aden', filter: 'hue-rotate(-20deg) contrast(.9) saturate(.85) brightness(1.2)' },
            { id: 2, name: 'Clarendon', filter: 'sepia(.15) contrast(1.25) brightness(1.25) hue-rotate(5deg)' },
            { id: 3, name: 'Crema', filter: 'sepia(.5) contrast(1.25) brightness(1.15) saturate(.9) hue-rotate(-2deg)' },
            { id: 4, name: 'Gingham', filter: 'contrast(1.1) brightness(1.1)' },
            { id: 5, name: 'Juno', filter: 'sepia(.35) contrast(1.15) brightness(1.15) saturate(1.8)' },
            { id: 6, name: 'Lark', filter: 'sepia(.25) contrast(1.2) brightness(1.3) saturate(1.25)' },
            { id: 7, name: 'Ludwig', filter: 'sepia(.25) contrast(1.05) brightness(1.05) saturate(2)' },
            { id: 8, name: 'Moon', filter: 'brightness(1.4) contrast(.95) saturate(0) sepia(.35)' },
            { id: 9, name: 'Original', filter: '' },
            { id: 10, name: 'Perpetua', filter: 'contrast(1.1) brightness(1.25) saturate(1.1)' },
            { id: 11, name: 'Reyes', filter: 'sepia(.75) contrast(.75) brightness(1.25) saturate(1.4)' },
            { id: 12, name: 'Slumber', filter: 'sepia(.35) contrast(1.25) saturate(1.25)' },
        ],
        adjustments: [
            { id: 1, name: 'Blur' },
            { id: 2, name: 'Brightness' },
            { id: 3, name: 'Contrast' },
            { id: 4, name: 'Grayscale' },
            { id: 5, name: 'Invert' },
            { id: 6, name: 'Opacity' },
            { id: 7, name: 'Saturate' },
            { id: 8, name: 'Sepia' },
            { id: 9, name: 'HueRotate' },
        ],
        emojis: {
            "popular": [
                { id: 1, emoji: '😎' },
                { id: 2, emoji: '❤' },
                { id: 3, emoji: '😍' },
                { id: 4, emoji: '😐' },
                { id: 5, emoji: '😂' },
                { id: 6, emoji: '😁' },
                { id: 7, emoji: '💖' },
                { id: 8, emoji: '😒' },
                { id: 9, emoji: '🌹' },
                { id: 10, emoji: '😜' },
            ],
            'activities': [
                { id: 1, emoji: '😎' },
                { id: 2, emoji: '😙' },
                { id: 3, emoji: '😚' },
                { id: 4, emoji: '🙂' },
                { id: 5, emoji: '🙄' },
                { id: 6, emoji: '😯' },
                { id: 7, emoji: '🤐' },
                { id: 8, emoji: '😯' },
                { id: 9, emoji: '🥱' },
                { id: 10, emoji: '😥' },
                { id: 11, emoji: '😌' },
                { id: 12, emoji: '😕' },
                { id: 13, emoji: '😒' },
                { id: 14, emoji: '🤤' },
                { id: 15, emoji: '😝' },
                { id: 16, emoji: '😜' },
                { id: 17, emoji: '🤑' },
                { id: 18, emoji: '😲' },
                { id: 19, emoji: '😤' },
                { id: 20, emoji: '😟' },
                { id: 21, emoji: '🤯' },
                { id: 22, emoji: '😩' },
                { id: 23, emoji: '😨' },
                { id: 24, emoji: '😧' },
                { id: 25, emoji: '😦' },
                { id: 26, emoji: '😭' },
                { id: 27, emoji: '🥵' },
                { id: 28, emoji: '😱' },
                { id: 29, emoji: '😡' },
                { id: 30, emoji: '😠' },
                { id: 31, emoji: '🦒' },
                { id: 32, emoji: '🐯' },
                { id: 33, emoji: '🦁' },
                { id: 34, emoji: '🐱' },
                { id: 35, emoji: '🐺' },
                { id: 36, emoji: '🐶' },
                { id: 37, emoji: '🐵' },
                { id: 38, emoji: '🦝' },
                { id: 39, emoji: '🐮' },
                { id: 40, emoji: '🐷' },
                { id: 41, emoji: '🐗' },
                { id: 42, emoji: '🐭' },
                { id: 43, emoji: '🐹' },
            ]
        }


    },
    reducers: {
        showCreateNewPost: (state) => { state.isShowCreateNewPost = true },
        hideCreateNewPost: (state) => { state.isShowCreateNewPost = false },
        setStepOfCreateNewPost: (state, action) => { state.step = action.payload },
        setIsOpenModal: (state, action) => { state.isOpenModal = action.payload },
    }
})

export const { showCreateNewPost, hideCreateNewPost, setStepOfCreateNewPost, setIsOpenModal } = createNewPostSlice.actions
export default createNewPostSlice.reducer